### PR TITLE
README.MD: added description, UI image, package needed, contribution procedure, tech stack

### PR DESCRIPTION
**Pull request by KumarSanu8**
README.MD: added description, UI image, package needed, contribution procedure, tech stack

### CODE REVIEW

**Comment by ratnakar5938** [comment]
🥲🥲 you did the same mistake again

**Comment by ratnakar5938** [comment]
Also delete the old stuff
That is not needed

**Comment by ratnakar5938** [comment]
Sorry bt this task is assigned to someone else

**Comment by KumarSanu8** [comment]
Please merge . its last day hacktoberfest , i improve to more thing in your
project and give to long time brother

**Pull request closed without merging**
