### PR TITLE
Basic Structure done need more changes

### LINKED ISSUE #1: Add Readme Documentation
**Sections to add** - 

- [ ] Logo
- [x] Description
- [x] Package Needed
- [x] Contribution procedure
- [x] Tech Stack
- [x] Contributors section

**Description** - 
Chat App made in React

**Tech Stack** - 
- React
- React-Chat-Engine

**Deployment** - 
- Netlify

**Package Manager** - 
- Yarn

### PR DESCRIPTION
**Pull request by namangirdhar16**
#1 

@ratnakar5938 i have added a basic template for readme only description and minute changes are required. Please see this and merge this once, rest changes i will do in another PR, it's just hacktoberfest is going to end soon and i'm left with one PR.

### CODE REVIEW

**Comment by ratnakar5938** [comment]
**Minor changes** -
- use yarn instead of npm
- add a section named demo under the description

@namangirdhar16

**Review by ratnakar5938 — CHANGES_REQUESTED** [review]
Use yarn instead of npm

**Comment by namangirdhar16** [comment]
@ratnakar5938 cool, i'll complete shortly.

**Comment by namangirdhar16** [comment]
@ratnakar5938 please have a look. It seems fine to me.

**Comment by ratnakar5938** [comment]
> @ratnakar5938 please have a look. It seems fine to me.

Cool🚀
Happy coding🔥

**Comment by ratnakar5938** [comment]
@all-contributors please add @ratnakar5938  for code, content, design, maintenance, review

**Comment by ratnakar5938** [comment]
@all-contributors please add @namangirdhar16  for documentation

**Review by ratnakar5938 — APPROVED** [review]

**Pull request merged**
